#!/usr/bin/env python3
import pandas

import seaborn as sns
import matplotlib.pyplot as plt

import numpy as np

sns.set(style="whitegrid")

data = pandas.read_csv('data.csv')
print(data)

my_dpi=96
plt.figure(figsize=(480/my_dpi, 480/my_dpi), dpi=my_dpi)

# multiple line plot
excluded = {19}
for i in set(data['id']):
    if i not in excluded:
        plt.plot(data[(data.id == i)]['frames'], data[(data.id == i)]['locX'], marker='', color='blue', linewidth=.5, alpha=0.2)
        plt.plot(data[(data.id == i)]['frames'], data[(data.id == i)]['locY'], marker='', color='orange', linewidth=.5, alpha=0.2)
for i in excluded:
    plt.plot(data[(data.id == i)]['frames'], data[(data.id == i)]['locX'], marker='', color='purple', linewidth=1, alpha=1.0)
    plt.plot(data[(data.id == i)]['frames'], data[(data.id == i)]['locY'], marker='', color='red', linewidth=1, alpha=1.0)

# Change xlim
# plt.xlim(0,12)

# Let's annotate the plot
#num=0
#for i in data.values[9][1:]:
#   num+=1
#   name=list(data)[num]
#   if name != 'y5':
#      plt.text(10.2, i, name, horizontalalignment='left', size='small', color='grey')
#
## And add a special annotation for the group we are interested in
#plt.text(10.2, data.y5.tail(1), 'Mr Orange', horizontalalignment='left', size='small', color='orange')
#
## Add titles
#plt.title("Evolution of Mr Orange vs other students", loc='left', fontsize=12, fontweight=0, color='orange')
#plt.xlabel("Time")
#plt.ylabel("Score")

plt.show()
