#!/usr/bin/env python3
import sys, os
from glob import glob

def main(args):
    for filename in glob('sources/*'):
        print(os.path.basename(filename)[:-4])
        with open(filename, 'r') as infile:
            content = infile.read()
        for line in content.split('\n'):
            if '@' in line:
                refname = line.split('@')[1].split(',')[0].split('{')[1]
                print('    ', refname)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
