#!/usr/bin/env python3
import os
from functools import partial

import pickle
import pandas
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from collections import defaultdict

sns.set(style="whitegrid")

data = pandas.read_csv('processed.csv')
data['clustering'] = data['count_400'] / max(data['id'])

processed = data.groupby(['frames']).mean().reset_index()
color = 'orange'
alpha = 1.0
linewidth = 2.0
plt.plot(processed['frames'], processed['clustering'], marker='', color=color, linewidth=linewidth, alpha=alpha)
plt.title('Average clustering coefficient over time (threshold = 400 pixels)')
plt.xlabel('Frames (Taken at 30hz)')
plt.ylabel('Clustering coefficient')
plt.show()
