#!/usr/bin/env python3
import pandas

import seaborn as sns
import matplotlib.pyplot as plt

import numpy as np

sns.set(style="whitegrid")

data = pandas.read_csv('modified.csv')

my_dpi=96
plt.figure(figsize=(480/my_dpi, 480/my_dpi), dpi=my_dpi)

# multiple line plot
excluded = {19}
for i in set(data['id']):
    if i in excluded:
        color = 'orange'
    else:
        color = 'black'
    alarmdata = data[(data.id == i)]
    for j in set(data['id']):
        if j != i:
            dj = 'd' + str(j)
            plt.plot(alarmdata['frames'], alarmdata[dj], marker='', color=color, linewidth=.5, alpha=0.2)

# Change xlim
# plt.xlim(0,12)

# Let's annotate the plot
#num=0
#for i in data.values[9][1:]:
#   num+=1
#   name=list(data)[num]
#   if name != 'y5':
#      plt.text(10.2, i, name, horizontalalignment='left', size='small', color='grey')
#
## And add a special annotation for the group we are interested in
#plt.text(10.2, data.y5.tail(1), 'Mr Orange', horizontalalignment='left', size='small', color='orange')
#
## Add titles
#plt.title("Evolution of Mr Orange vs other students", loc='left', fontsize=12, fontweight=0, color='orange')
#plt.xlabel("Time")
#plt.ylabel("Score")

plt.show()
