#!/usr/bin/env python3
import os
from functools import partial


import pandas
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

sns.set(style="whitegrid")

if not os.path.isfile('summed_distances.csv'):
    data = pandas.read_csv('modified.csv')

    my_dpi=96
    plt.figure(figsize=(480/my_dpi, 480/my_dpi), dpi=my_dpi)
    ids = set(data['id'])
    data['distances_sum'] = sum(data['d{}'.format(i)] for i in ids)
    data.to_csv('summed_distances.csv')
data = pandas.read_csv('summed_distances.csv')
excluded = {19}
for i in set(data['id']):
    if i in excluded:
        color = 'orange'
        alpha = 1.0
        linewidth = 2.0
    else:
        color = 'black'
        alpha = 0.2
        linewidth = 0.5
    alarmdata = data[(data.id == i)]
    plt.plot(alarmdata['frames'], alarmdata['distances_sum'], marker='', color=color, linewidth=linewidth, alpha=alpha)
#plt.plot(data['frames'], data['distances_sum'], marker='', color='orange')
plt.title('Sum of ant distances over time')
plt.xlabel('Frames (Taken at 30hz)')
plt.ylabel('Sum of pixel distances between all ants')
plt.show()
