#!/usr/bin/env python3
import pandas

import seaborn as sns
import matplotlib.pyplot as plt

import numpy as np

sns.set(style="whitegrid")

data = pandas.read_csv('data.csv')
# Load the example iris dataset

# Draw a scatter plot while assigning point colors and sizes to different
# variables in the dataset
f, ax = plt.subplots(figsize=(12, 12))
sns.despine(f, left=True, bottom=True)

# Data columns
# ['id' 'frames' 'locX' 'locY' 'orientation' 'size1 (px)' 'size2 (px)' 'speed (px/s)' 'Interpolated']

data = data[data.id == 19]
sns.scatterplot(x='frames', y='speed (px/s)', palette='blue', data=data, ax=ax, linewidth=0)
#sns.scatterplot(x='frames', y='locY', palette='blue', data=data, ax=ax, linewidth=0)

#print(data)
#
#
#data = pandas.pivot_table(data, values='speed (px/s)', index=['frames'], aggfunc=np.mean)
#data = data.reset_index()
#
#sns.scatterplot(x='frames',
#                y='speed (px/s)',
#                #hue='clarity', 
#                #hue='orientation',
#                #palette="ch:r=-.2,d=.3_r",
#                #hue_order=clarity_ranking,
#                #alpha=0.3,
#                #sizes=[0.5], 
#                #linewidth=0,
#                data=data, ax=ax)

plt.show()
