#!/usr/bin/env python3
import pandas

import seaborn as sns
import matplotlib.pyplot as plt

import numpy as np

import math

sns.set(style="whitegrid")

data = pandas.read_csv('data.csv')
for i in set(data['id']):
    print(i)
    def calc_distances(row):
        frame   = row.frames
        current = data[((data.frames == frame) & (data.id == i))]
        x = list(current['locX'])[0]
        y = list(current['locY'])[0]
        dx = x - row.locX 
        dy = y - row.locY
        dist = math.sqrt(dx**2 + dy**2)
        return dist

    colname = 'd{}'.format(i)
    data[colname] = data.apply(calc_distances, axis=1)
    #break

data.to_csv('modified.csv')
