#!/usr/bin/env python3
import os, sys
from functools import partial

import pickle
import pandas
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from collections import defaultdict

from sum_distance_thresholds import main as sum_thresholds

def main(args):
    for i in range(1, 10):
        threshold = 10 * i
        sum_thresholds(['processed.csv', 'processed.csv', threshold])
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
