#!/usr/bin/env python3
import os, sys
from functools import partial
from collections import defaultdict
from copy import deepcopy

import pickle
import pandas
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

ids    = list(range(61))
color     = 'red'
alpha     = 1.0
linewidth = 1.8
dense     = True

sns.set(style='whitegrid')

def main(args):
    assert len(args) == 1, 'Usage: ./time_interactions [data.csv]'
    filename = args[0]

    interactions = defaultdict(list)
    with open(filename, 'r') as infile:
        lines = infile.read().split('\n')
        for line in lines[1:]:
            if line.strip() != '':
                #t, a, b = list(map(lambda s : int(s.strip()), line.split(',')))
                b, a, _, t = list(map(lambda s : int(s.strip()), line.split(',')))
                t *= 30
                interactions[t].append((a, b))

    frames = list(range(max(interactions.keys())))

    active= 0
    activeY = []
    signal_paths = {}

    for i in frames:
        if i in interactions:
            for interaction in interactions[i]:
                source, destination = interaction
                plt.plot(frames[i:i+2], [source, destination], linestyle='--')

    for i in ids:
        plt.plot(frames, [i] * len(frames), marker='', color='grey', linewidth=0.6, alpha=0.5)

    time_unit_label = 'Frames (30hz)'
    
    plt.title('Temporal network interactions')
    plt.xlabel(time_unit_label)
    plt.ylim(0, 61)
    plt.ylabel('Ant ID')
    plt.savefig('network_interactions.png', dpi=300)
    plt.show()

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
