#!/usr/bin/env python3
import os, sys
from functools import partial
from collections import defaultdict
from copy import deepcopy

import pickle
import pandas
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

ids    = list(range(61))
color     = 'red'
alpha     = 1.0
linewidth = 1.8
dense     = True

sns.set(style='whitegrid')

norm = lambda x : max(min(x, 1.0), 0.0)

interactionOpacity = 1.0
#anticolors = [(0.0, 1.0, 1.0), (51/255, 51/255, 201/255), (204/255, 51/255, 255/255), (0.0, 1.0, 0.0), (1.0, 153/255, 1.0), (1.0, 204/255, 0.0), (153/255, 0.0, 153/255)]

anticolors = [((2 ** n)/255,) * 3 for n in range(8)]
anticolors = [c + (interactionOpacity,) for c in anticolors]

def colorize(strength, discrete=True):
    if discrete:
        if strength > 0.749: # Alarmed threshold (Red)
            return (1.0, 0.0, 0.0)
        elif strength > 0.305: # Alert threshold (Blue)
            return (0.0, 0.0, 1.0)
        else: # Standard (White)
            return (1.0, 1.0, 1.0)
    else:
        return (1.0, 0.0, 0.0, norm(strength))


def main(args):
    alarmData = pandas.read_csv('alarm_strengths_seconds.csv')
    assert len(args) == 1, 'Usage: ./time_interactions [data.csv]'
    filename = args[0]

    interactions = defaultdict(list)
    with open(filename, 'r') as infile:
        lines = infile.read().split('\n')
        for line in lines[1:]:
            if line.strip() != '':
                b, a, _, t = list(map(lambda s : int(s.strip()), line.split(',')))
                interactions[t].append((a, b))

    frames = list(range(max(interactions.keys())))

    for alarmRow in alarmData.iterrows():
        i = alarmRow[0]
        strength = alarmRow[1]
        for j in ids:
            plt.plot([i, i+1], [j, j], color=colorize(strength[j]))
        print(i)
    for i in frames:
        if i in interactions:
            for j, interaction in enumerate(interactions[i]):
                source, destination = interaction
                color = anticolors[j % len(anticolors)]
                plt.plot([i,i+1], [source, destination], linestyle='--', marker='.', color=color,
                         linewidth=1.5, markersize=7,
                         dashes=(5, 5))
        print(i)

    #for i in ids:
    #    #plt.plot(frames, [i] * len(frames), marker='', color='grey', linewidth=0.6, alpha=0.5)

    time_unit_label = 'Seconds (30hz)'
    
    plt.title('Temporal network interactions')
    plt.xlabel(time_unit_label)
    plt.ylim(0, 61)
    plt.ylabel('Ant ID')
    plt.savefig('network_interactions.png', dpi=300)
    plt.show()

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
