#!/usr/bin/env python3
import os
from functools import partial


import pandas
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

def plot_data(data, ax, maximum=None):
    excluded = {}
    for i in set(data['id']):
        if i in excluded:
            color = 'orange'
            alpha = 1.0
            linewidth = 2.0
        else:
            color = 'black'
            alpha = 0.2
            linewidth = 0.5
        alarmdata = data[(data.id == i)]
        ax.plot(alarmdata['frames'], alarmdata['speed (px/s)'], marker='', color=color, linewidth=linewidth, alpha=alpha)
    ax.plot(list(sorted(set(data['frames']))), data.groupby(['frames'])['speed (px/s)'].mean(), marker='', color='orange')
    if maximum is not None:
        ax.set_ylim(0.0, maximum)
    ax.set_xlabel('Frames (Taken at 30hz)')
    ax.set_ylabel('Speed (px/s)')

sns.set(style="whitegrid")

fig, (ax1, ax2) = plt.subplots(nrows=2, sharex=True)

Colony71 = pandas.read_csv('S1700006-.csv')
Colony45 = pandas.read_csv('S1660003__0-00-02_Results.csv')

max_velocity = max(Colony71['speed (px/s)'].max(), Colony45['speed (px/s)'].max())
plot_data(Colony71, ax1, max_velocity)
ax1.set_title('Spaghetti plot of ant speeds over time For colony 71')
plot_data(Colony45, ax2, max_velocity)
ax2.set_title('Spaghetti plot of ant speeds over time For colony 45')
plt.show()
