#!/usr/bin/env python3
import os
from functools import partial

import pickle
import pandas
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from collections import defaultdict

sns.set(style="whitegrid")

def main():
    general_data = pandas.read_csv('S1700006-.csv')
    print(set(general_data['id']))

    speed_data = general_data.pivot_table(index='frames', columns='id', values='speed (px/s)')
    orientation_data = general_data.pivot_table(index='frames', columns='id', values='orientation')

    fig, (ax1, ax2) = plt.subplots(nrows=2, sharex=True)
    fig.subplots_adjust(hspace=0.0)
    global_kwargs = dict(cbar=True,cbar_kws={"shrink": .82}, vmin=0.0, vmax=1.0)
    sns.heatmap(orientation_data, xticklabels=speed_data.columns.values, cbar=True, cbar_kws={'shrink' : 0.82}, ax=ax1)
    sns.heatmap(speed_data,       xticklabels=speed_data.columns.values, cbar=True, cbar_kws={'shrink' : 0.82}, ax=ax2)
    plt.show()
    #print(preference_data)

main()
