#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

u1 = 1.0
u2 = 7.0
s1 = 0.5
s2 = 1.5

N = 500
p1 = [np.random.normal(u1, s1) for i in range(N)]
p2 = [np.random.normal(u2, s2) for i in range(N)]

plt.plot(p1)
plt.plot(p2)
plt.show()
