#!/usr/bin/env python3
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import pandas
import math
import sys

sns.set_style('darkgrid')

def main(args):
    colony = 71

    if colony == 45:
        experiment = pandas.read_csv('C45Active1C.csv')
        control    = pandas.read_csv('C45Control1C.csv')
    elif colony == 71:
        experiment = pandas.read_csv('C71Active1C.csv')
        control    = pandas.read_csv('C71Control1C.csv')

    #experiment = pandas.read_csv('C71Active1C.csv')
    #control    = pandas.read_csv('C71TA3T.csv')

    #plot_original(experiment, control, colony)
    #experiment = experiment[(experiment['speed (px/s)'] > 3)]
    #control    = control[(control['speed (px/s)'] > 3)]
    
    maxSpeed = 100.0

    experiment['type'] = 'experiment'
    control['type']    = 'control'
    data = pandas.concat([experiment, control])
    data['second'] = data['frames'] // 30 # Convert frames to seconds
    data['period'] = data['second'] // 20 # Define a period as thirty seconds
    print(data)
    #data = data.groupby('period')

    #data['speed'] = data['speed (px/s)'].apply(lambda x :  0 if x < 1e-7 else max(0, math.log(x, 10)))
    data['speed'] = data['speed (px/s)'].apply(lambda x : max(0, min(x, maxSpeed)))
    sns.violinplot(x='period', y='speed', hue='type', data=data, palette='muted', split=True)
    plt.xlabel('Period (20 seconds)')
    plt.ylabel('Distribution of speeds in pixels/second')
    plt.title('Changes in the distribution of speeds over time for colony {}'.format(colony))
    fig = matplotlib.pyplot.gcf()
    fig.set_size_inches(18.5, 10.5)
    fig.savefig('violin_{}.png'.format(colony), dpi=300)
    plt.show()

def plot_original(experiment, control, colony):
    experiment_medians = experiment.groupby('frames').median()
    control_medians    = control.groupby('frames').median()
    #print(experiment_medians)
    #1/0

    experiment_frames = experiment[experiment.id == 1]['frames'][1:]
    experiment_speeds = experiment_medians['speed (px/s)'][1:]
    control_frames    = control[control.id == 1]['frames'][1:]
    control_speeds    = control_medians['speed (px/s)'][1:]

    plt.plot(experiment_frames, experiment_speeds, color='orange')
    plt.plot(control_frames, control_speeds, color='black')
    plt.xlabel('Frames (30hz)')
    plt.ylabel('Average speed (px/s)')
    plt.title('Comparison between alarmed and control for colony 45 setting 1')
    plt.savefig('medians_{}.png'.format(colony))
    plt.show()

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
